### ISSUE TITLE
Utils and other dependencies are taken for granted and not in package.json 

### ISSUE THREAD

**Issue by hugomosh** [spark/softap-setup-js#36]
I just install it to react native but utils was not found, so I had to manually install it. Not sure if it is an issue.

**Comment by hugomosh** [comment]
Sorry, I rushed, I saw that I need to broweserfy it https://github.com/philikon/ReactNativify 
o use webpack. Anyone has use it with react native that can help me?

**Comment by btav** [comment]
@hugomosh Unfortunately using this library with react-native requires a lot hacking because its using node modules that you do not have access to using react-native since it uses JavaScript Core as its JS runtime. 

If your going with the React-Nativify approach, instead of creating your own babel transforms inside a `transformer.js`, inside of `rn-cli.config.js` you can export extraNodeModules and override node modules. For more information check out this issue on ReactNativify's repo https://github.com/philikon/ReactNativify/issues/4

The way we got around this problem was to simply just use HTTP requests. Once the photon is in listening mode (flashing blue), you can join its wifi and send it commands via HTTP to configure wifi. We used the following documentation...
https://github.com/kbowerma/particle/blob/master/photon_firmware/firmware/hal/src/photon/soft-ap.md#commands

Also, @steelydev created a sample program that simply uses HTTP requests to configure wifi. https://github.com/spark/softap-setup-js/issues/22

I hope this LONG answer helps :)

**Comment by hugomosh** [comment]
Yes I ended up making the hole connection process by our own using react-native friendly libraries. The hard one was the ones related to crypto (keys) 

Thanks @btav

**Comment by m-mcgowan** [comment]
Sounds like you got a resolution. I'll close this issue - feel free to reopen if there are further points to discuss.
